import { Router } from 'express';
import { authRouter } from './auth.routes';
import { eventsRouter } from './events.routes';
import { tasksRouter } from './tasks.routes';
import { peopleRouter } from './people.routes';
import { checklistRouter } from './checklist.routes';
import { templatesRouter } from './templates.routes';
import { tagsRouter } from './tags.routes';
import { commentsRouter } from './comments.routes';
import { attachmentsRouter } from './attachments.routes';
import { notesRouter } from './notes.routes';
import { activityRouter } from './activity.routes';
import { notificationsRouter } from './notifications.routes';
import { dashboardRouter } from './dashboard.routes';
import { plannerRouter } from './planner.routes';
import { calendarRouter } from './calendar.routes';
import { searchRouter } from './search.routes';
import { attentionRouter } from './attention.routes';
import { reportsRouter } from './reports.routes';
import { settingsRouter } from './settings.routes';

export const apiRouter = Router();

apiRouter.use('/auth', authRouter);
apiRouter.use('/events', eventsRouter);
apiRouter.use('/tasks', tasksRouter);
apiRouter.use('/people', peopleRouter);
apiRouter.use('/checklist-items', checklistRouter);
apiRouter.use('/templates', templatesRouter);
apiRouter.use('/tags', tagsRouter);
apiRouter.use('/comments', commentsRouter);
apiRouter.use('/attachments', attachmentsRouter);
apiRouter.use('/notes', notesRouter);
apiRouter.use('/activity', activityRouter);
apiRouter.use('/notifications', notificationsRouter);
apiRouter.use('/dashboard', dashboardRouter);
apiRouter.use('/planner', plannerRouter);
apiRouter.use('/calendar', calendarRouter);
apiRouter.use('/search', searchRouter);
apiRouter.use('/attention', attentionRouter);
apiRouter.use('/reports', reportsRouter);
apiRouter.use('/settings', settingsRouter);
