/** Default checklist auto-applied to every newly created event. */
export const DEFAULT_EVENT_CHECKLIST: readonly string[] = [
  'Event Proposal',
  'Approval',
  'Budget Planning',
  'Venue Booking',
  'Chief Guest',
  'Invitation',
  'Poster Design',
  'Banner Design',
  'Social Media Poster',
  'Registration Form',
  'Registration Link',
  'Certificates',
  'ID Cards',
  'Memento',
  'Stage Backdrop',
  'Photography',
  'Videography',
  'Volunteer Allocation',
  'Sound System',
  'Refreshments',
  'Attendance',
  'Sponsors',
  'Agenda',
  'Script',
  'Anchoring Notes',
  'Presentation PPT',
  'Participant List',
  'Feedback Form',
  'Thank You Post',
  'Report',
  'Expense Sheet',
  'Completion Report',
  'Archive',
];

/** Seed set of built-in checklist templates, keyed by template name -> item labels. */
export const BUILT_IN_TEMPLATES: Record<string, readonly string[]> = {
  Seminar: [
    'Event Proposal',
    'Approval',
    'Budget Planning',
    'Venue Booking',
    'Chief Guest',
    'Invitation',
    'Poster Design',
    'Registration Form',
    'Certificates',
    'Attendance',
    'Feedback Form',
    'Report',
  ],
  Workshop: [
    'Event Proposal',
    'Approval',
    'Budget Planning',
    'Venue Booking',
    'Registration Form',
    'Participant List',
    'Presentation PPT',
    'Certificates',
    'Feedback Form',
    'Report',
  ],
  Conference: [...DEFAULT_EVENT_CHECKLIST],
  Installation: [
    'Event Proposal',
    'Approval',
    'Budget Planning',
    'Venue Booking',
    'Chief Guest',
    'Invitation',
    'Poster Design',
    'Banner Design',
    'Stage Backdrop',
    'Photography',
    'Videography',
    'Sound System',
    'Refreshments',
    'Memento',
    'Report',
  ],
  'Medical Camp': [
    'Event Proposal',
    'Approval',
    'Budget Planning',
    'Venue Booking',
    'Volunteer Allocation',
    'Registration Form',
    'Attendance',
    'Sponsors',
    'Photography',
    'Completion Report',
  ],
  'Training Program': [
    'Event Proposal',
    'Approval',
    'Budget Planning',
    'Venue Booking',
    'Registration Form',
    'Agenda',
    'Presentation PPT',
    'Participant List',
    'Certificates',
    'Feedback Form',
    'Report',
  ],
  'Awareness Program': [
    'Event Proposal',
    'Approval',
    'Venue Booking',
    'Poster Design',
    'Social Media Poster',
    'Volunteer Allocation',
    'Photography',
    'Report',
  ],
};
